keybind = alt+space=toggle_quick_terminal
quick-terminal-position = top
quick-terminal-size = 35%,99%
quick-terminal-autohide = false
quick-terminal-keyboard-interactivity = exclusive
background-opacity = 0.97
